language: ruby
sudo: false
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.3
  - 2.2.0-preview1
  - jruby-18mode
  - jruby-19mode
  - rbx-2
  - ruby-head
  - jruby-head
  - ree
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
